### PR TITLE
Adding support for maxVideoDuration, setting project settings for Swift 2.3 and adding .gitignore.

### PR DESCRIPTION
**Pull request by pcoltau**

### CODE REVIEW

**Comment by mjrehder** [comment]
Please add a "select video button" as an example in the demo project in order to test the video option.

**Comment by pcoltau** [comment]
@mjrehder: Fixed. Please re-review.

**Review by mjrehder — CHANGES_REQUESTED** [review]
An error occurs on runtime:
2016-10-08 16:42:10.746033 Demo[2015:1123381] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by mjrehder** [comment]
Also access to microphone is missing: NSMicrophoneUsageDescription in the info.plist

**Comment by mjrehder** [comment]
The following logs were seen when recording:
2016-10-08 16:47:44.965923 Demo[2025:1125562] [Camera] Encountered an error during video recording! (duration: <private> error: <private>, file: <private>)
2016-10-08 16:47:44.966862 Demo[2025:1125562] [Camera] Attempting to recover from movie fragments…
2016-10-08 16:47:45.054933 Demo[2025:1125562] [Camera] Successfully recovered movie fragments into a usable movie file.
2016-10-08 16:47:45.092881 Demo[2025:1125562] [Camera] Replaced duration with asset duration 10.541667 (reportedDuration was <private>)

It seems to be OK, the video recording stops automatically after 10s (as specified by the demo) - The logging might be too verbose due to iOS 10 debug log settings.

**Comment by pcoltau** [comment]
@mjrehder Added the Usage Descriptions to the plist file for the demo. Please re-review.

**Pull request merged**
